Summary:	Netlist comparison (LVS) and format manipulation tool
Name:		netgen
Version:	1.5.287
Release:	1
License:	GPL+
Group:		Sciences/Mathematics
URL:		http://opencircuitdesign.com/netgen
Source0:	http://opencircuitdesign.com/%{name}/archive/%{name}-%{version}.tgz
# (fedora)
# this png is a screenshot taken on adder4 (an alliance's example) by Chitlesh
# its license is GPL+
Source1:	%{name}.png

BuildRequires:	imagemagick
BuildRequires:	pkgconfig(python3)
BuildRequires:	pkgconfig(tk)
BuildRequires:	pkgconfig(x11)

%description
Netgen is a tool for comparing netlists, a process known as LVS, which
stands for "Layout vs. Schematic".  This is an important step in the
integrated circuit design flow, ensuring that the geometry that has
been laid out matches the expected circuit.   Very small circuits can
bypass this step by confirming circuit operation through extraction and
simulation.  Very large digital circuits are usually generated by tools
from high-level descriptions, using compilers that ensure the correct
layout geometry. The greatest need for LVS is in large analog or
mixed-signal circuits that cannot be simulated in reasonable time.  Even
for small circuits, LVS can be done much faster than simulation, and
provides feedback that makes it easier to find an error than does a
simulation. 

%files
%license Copying
%doc README.md VERSION TO_DO Changes netgen.doc
%{_bindir}/%{name}
%{_libdir}/%{name}/
%{_iconsdir}/hicolor/*/apps/%{name}.png
%{_datadir}/pixmaps/%{name}.xpm
%{_datadir}/applications/*%{name}.desktop

#-----------------------------------------------------------------------

%prep
%autosetup -p1

# fix lib path
sed -i \
	-e "s,@DIST_DIR@/lib,@DIST_DIR@/%{_lib}," \
	-e "s,\${INSTALL_LIBDIR}/netgen/doc,%{_datadir}/doc/netgen," \
	scripts/defs.mak.in

%build
# This package contains many implicit function declarations.
%global build_type_safety_c 0
%configure \
	--with-x
%make_build

%install
%make_install

# fix permissions
for f in ntk2adl.sh spice
do
	chmod 0755 %{buildroot}%{_libdir}/%{name}/${f}
done

# icon
for d in 16 32 48 64 72 128 256
do
	install -dm 0755 %{buildroot}%{_iconsdir}/hicolor/${d}x${d}/apps/
	convert -scale ${d}x${d} %{SOURCE1} \
		%{buildroot}%{_iconsdir}/hicolor/${d}x${d}/apps/%{name}.png
done
install -dm 0755 %{buildroot}%{_datadir}/pixmaps/
convert -scale 32x32 %{SOURCE1} %{buildroot}%{_datadir}/pixmaps/%{name}.xpm

# .desktop file
install -dm 0755 %{buildroot}%{_datadir}/applications/
cat > %{buildroot}%{_datadir}/applications/openmandriva-%{name}.desktop << EOF
[Desktop Entry]
Name=%{name}
Comment="LVS comparison tool"
Exec=%{name}
Icon=%{name}
Terminal=false
Type=Application
StartupNotify=false
Categories=System;
X-Vendor=OpenMandriva
EOF
